#!/usr/bin/env python

import rospy
from motor_driver import MotorDriver

class MotorDriverROSWrapper:

    def __init__(self):
        self.motor = MotorDriver()

    def stop(self):
        self.motor.stop()
        

if __name__ == "__main__":
    rospy.init_node("motor_driver")

    motor_driver_wrapper = MotorDriverROSWrapper()
    rospy.on_shutdown(motor_driver_wrapper.stop)

    rospy.loginfo("Motor driver is now started, ready to get commands.")
    rospy.spin()