#!/usr/bin/env python

import rospy
import motor_driver as motor
if __name__ == "__main__":
    rospy.init_node("motor_driver")

    rospy.on_shutdown(motor.stop())

    rospy.loginfo("Motor driver is now started, ready to get commands.")
    rospy.spin()